[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt", args = ["--config", "struct_field_align_threshold=32,enum_discrim_align_threshold=32"] }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language.debugger]
name = "lldb"
command = "lldb-dap"
transport = "stdio"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [{ name = "binary", completion = "filename" }]
args = { program = "{0}", console = "internalConsole", initCommands = ["command script import /home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/etc/lldb_lookup.py", "command source -s 0 /home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/etc/lldb_commands"] }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = ["pid"]
args = { console = "internalConsole", pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [
  { name = "lldb connect url", default = "connect://localhost:3333" },
  { name = "file", completion = "filename" },
  "pid",
]
args = { console = "internalConsole", attachCommands = ["platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "gofmt", args = [] }
language-servers = [ "gopls", "gpt" ]

[language-server.gopls]
command = "gopls"

[[language]]
name = "zig"
file-types = [ "zig", "zon" ]
auto-format = true
formatter = { command = "zig", args = [ "fmt" ] }
language-servers = [ "zls" ]

[language-server.zls]
command = "zls"

[language.debugger]
name = "lldb"
command = "lldb-dap"
transport = "stdio"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [{ name = "binary", completion = "filename" }]
args = { program = "{0}", console = "internalConsole", initCommands = [] }

[[language]]
name = "bash"
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "json"
auto-format = true
formatter = { command = "dprint", args = [ "fmt", "--stdin", "json" ] }
language-servers = ["vscode-json-language-server"]

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "dprint", args = [ "fmt", "--stdin", "json" ] }
language-servers = ["yaml-language-server"]

[language-server.yaml-language-server]
command = "yaml-language-server"

[language-server.gpt]
command = "helix-gpt"
args = [ "--handler", "codeium", "--codeiumApiKey", "35ffec80-f036-464e-b1b0-4561faeae0dd" ]
